
import __ASTRO_IMAGE_IMPORT_1ekvKI from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2022-11-post-27-2023-cfp-announcement.md";
import __ASTRO_IMAGE_IMPORT_1B3Bzf from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-03-post-27-2023-cfp_closure.md";
import __ASTRO_IMAGE_IMPORT_Z1Ye7kY from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-1.md";
import __ASTRO_IMAGE_IMPORT_Z1xj9kk from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-09-post-2.md";
import __ASTRO_IMAGE_IMPORT_Z1YdQke from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-3.md";
import __ASTRO_IMAGE_IMPORT_j003X from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-02-post-04-2023_cfp_announcement.md";
import __ASTRO_IMAGE_IMPORT_Z1fvWAy from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fbrandon-lester.md";
export default new Map([["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2022-11-post-27-2023-cfp-announcement.md", __ASTRO_IMAGE_IMPORT_1ekvKI], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-03-post-27-2023-cfp_closure.md", __ASTRO_IMAGE_IMPORT_1B3Bzf], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-1.md", __ASTRO_IMAGE_IMPORT_Z1Ye7kY], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-09-post-2.md", __ASTRO_IMAGE_IMPORT_Z1xj9kk], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-3.md", __ASTRO_IMAGE_IMPORT_Z1YdQke], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-02-post-04-2023_cfp_announcement.md", __ASTRO_IMAGE_IMPORT_j003X], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fbrandon-lester.md", __ASTRO_IMAGE_IMPORT_Z1fvWAy]]);
		