
import __ASTRO_IMAGE_IMPORT_1ekvKI from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2022-11-post-27-2023-cfp-announcement.md";
import __ASTRO_IMAGE_IMPORT_1B3Bzf from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-03-post-27-2023-cfp_closure.md";
import __ASTRO_IMAGE_IMPORT_Z1YdQke from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-3.md";
import __ASTRO_IMAGE_IMPORT_j003X from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-02-post-04-2023_cfp_announcement.md";
import __ASTRO_IMAGE_IMPORT_Z1Ye7kY from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-1.md";
import __ASTRO_IMAGE_IMPORT_Z1xj9kk from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-09-post-2.md";
import __ASTRO_IMAGE_IMPORT_Z1fvWAy from "../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fbrandon-lester.md";
import __ASTRO_IMAGE_IMPORT_ZUGJw6 from "../../../images/BenEldrich.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fben-eldrich.md";
import __ASTRO_IMAGE_IMPORT_Z1toeib from "../../../images/anonymous.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Faaron-mcphall.md";
import __ASTRO_IMAGE_IMPORT_20OQeq from "../../../images/JeffHoge.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fjeff-hoge.md";
import __ASTRO_IMAGE_IMPORT_1aTEr4 from "../../../images/BrianMaloney.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fbrian-maloney.md";
import __ASTRO_IMAGE_IMPORT_ZTkgLK from "../../../images/kennedy.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fkennedy-toomey.md";
import __ASTRO_IMAGE_IMPORT_Z2paLwM from "../../../images/larry.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Flarry-whiteside-jr.md";
import __ASTRO_IMAGE_IMPORT_Z1Cri1R from "../../../images/logan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Flogan-diomedi.md";
import __ASTRO_IMAGE_IMPORT_14tklk from "../../../images/tweeks.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Ftom-weeks.md";
import __ASTRO_IMAGE_IMPORT_1DpotK from "../../../images/anonymous.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fwally-prather.md";
export default new Map([["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2022-11-post-27-2023-cfp-announcement.md", __ASTRO_IMAGE_IMPORT_1ekvKI], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-03-post-27-2023-cfp_closure.md", __ASTRO_IMAGE_IMPORT_1B3Bzf], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-3.md", __ASTRO_IMAGE_IMPORT_Z1YdQke], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-02-post-04-2023_cfp_announcement.md", __ASTRO_IMAGE_IMPORT_j003X], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2023-10-post-1.md", __ASTRO_IMAGE_IMPORT_Z1Ye7kY], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2F2024-09-post-2.md", __ASTRO_IMAGE_IMPORT_Z1xj9kk], ["../../../public/b-sides-roanoke.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fbrandon-lester.md", __ASTRO_IMAGE_IMPORT_Z1fvWAy], ["../../../images/BenEldrich.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fben-eldrich.md", __ASTRO_IMAGE_IMPORT_ZUGJw6], ["../../../images/anonymous.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Faaron-mcphall.md", __ASTRO_IMAGE_IMPORT_Z1toeib], ["../../../images/JeffHoge.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fjeff-hoge.md", __ASTRO_IMAGE_IMPORT_20OQeq], ["../../../images/BrianMaloney.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fbrian-maloney.md", __ASTRO_IMAGE_IMPORT_1aTEr4], ["../../../images/kennedy.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fkennedy-toomey.md", __ASTRO_IMAGE_IMPORT_ZTkgLK], ["../../../images/larry.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Flarry-whiteside-jr.md", __ASTRO_IMAGE_IMPORT_Z2paLwM], ["../../../images/logan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Flogan-diomedi.md", __ASTRO_IMAGE_IMPORT_Z1Cri1R], ["../../../images/tweeks.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Ftom-weeks.md", __ASTRO_IMAGE_IMPORT_14tklk], ["../../../images/anonymous.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fwally-prather.md", __ASTRO_IMAGE_IMPORT_1DpotK]]);
		